#!/bin/sh -e

SERVICES="crond ip6tables iptables local"

if [ $(id -u) -ne 0 ]; then
  echo "This script can only be run by root!" >&2
  exit 1
fi

echo "Installing required packages ..."
apk update
apk add \
  curl \
  doas-sudo-shim \
  docker-cli-compose@edge \
  docker-rootless-extras@edge \
  docs \
  drill \
  ip6tables \
  iptables \
  iproute2 \
  keychain \
  mandoc \
  patch \
  tmux

rm -f /etc/profile.d/*.disabled

if type -P tmux > /dev/null && [ ! grep -q tmux /etc/shells ]; then
  echo
  echo "Configuring additional login shells..."
  type -P tmux | tee -a /etc/shells
fi

if type -P dockerd-rootless > /dev/null; then
  echo
  echo "Enabling cgroups v2 required by docker-rootless ..."
  sed -i -E 's/#(rc_cgroup_mode)=".*"/\1="unified"/' /etc/rc.conf
  SERVICES="${SERVICES} cgroups"
  /usr/local/sbin/setup-subids
fi

echo
for service in ${SERVICES}; do
  if rc-service --exists $service; then
    rc-update add $service default
  fi
done
unset service

# Create patches with:
#   diff -dw /path/to/file.orig /path/to/file
echo
for patch in /root/*.patch; do
  ( cd / && patch -ubf -p0 -i "${patch}" || true )
done

echo
echo "Running setup-alpine ..."
/sbin/setup-alpine -f "/root/${0##*/}.answers"
