#!/bin/sh -e

if [ $(id -u) -ne 0 ]; then
  echo "ERROR: This script can only be run by root!" >&2
  exit 1
fi

apk upgrade

echo "Installing basic environment ..."
apk add \
  docs mandoc curl \
  git github-cli delta lazygit lazydocker \
  ripgrep fd sd xh jq yq bottom bandwhich hyperfine \
  terraform

echo "Installing bash and tools ..."
apk add bash bash-completion shellcheck bats shellspec

echo "Installing neovim and tools ..."
apk add neovim g++ libstdc++ npm lua-language-server tree-sitter-cli
npm install -g bash-language-server

echo "Installing ruby and gems ..."
apk add ruby ruby-rdoc ruby-dev make
gem update --system
gem update
gem cleanup
gem install gem-browse rubocop rubocop-md rubocop-performance rubocop-rake rubocop-rspec pry pry-byebug solargraph

echo "Installing crystal and shards ..."
apk add crystal
