#!/bin/sh -e

if [ $(id -u) -ne 0 ]; then
  echo "This script can only be run by root!" >&2
  exit 1
fi

: "${ICLOUD_MNT:=/mnt}"
: "${APKOVL:=$ICLOUD_MNT/apkovl}"
: "${ISHOVL:=$ICLOUD_MNT/apkovl/root/ish}"
: "${ISH_DOCUMENTS_MNT:=/tmp/iSH}"

if ! mount | grep -q "on ${ICLOUD_MNT} type"; then
  echo "Mounting iSH cloud storage: ... ${ICLOUD_MNT}"
  mkdir -p "${ICLOUD_MNT}"
  mount -t ios . "${ICLOUD_MNT}"
fi

echo
echo "Customising iSH filesystem ..."
for file in $(cd "${APKOVL}" && find . -type f); do
  source="${APKOVL}${file:1}"
  target="${file:1}"
  mkdir -p "$(dirname "${target}")"
  rm -f "${target}"
  install -vD "${source}" "${target}"
done
unset file

if ! mount | grep -q "on ${ISH_DOCUMENTS_MNT} type"; then
  echo "Mounting iSH resources: ... ${ISH_DOCUMENTS_MNT}"
  mkdir -p "${ISH_DOCUMENTS_MNT}"
  mount -t real "$(cat /proc/ish/documents)" "${ISH_DOCUMENTS_MNT}"
fi

echo
echo "Customising iSH resources ..."
for file in $(cd "${ISHOVL}" && find . -type f); do
  source="${ISHOVL}${file:1}"
  target="${ISH_DOCUMENTS_MNT}${file:1}"
  install -vD -m 0644  "${source}" "$(dirname "${target}")"
done
unset file

echo
echo "Initialising OpenRC ..."
sed -i -E "3s/\ssysinit//" /etc/inittab
sed -i -E "s/^(tty[2-6])/# \1/" /etc/inittab

echo
echo "Installing alpine packages ..."
apk upgrade
apk add \
    busybox-openrc \
    busybox-suid \
    curl \
    doas-sudo-shim \
    docker \
    docker-cli-compose \
    docs \
    mandoc \
    openrc \
    openssh \
    \
    abduco@edge \
    bandwhich@edge \
    bash \
    bash-completion \
    delta \
    expect \
    fd \
    git \
    github-cli \
    hyperfine \
    jq \
    keychain \
    lazygit \
    lazydocker \
    ripgrep \
    sd@edge \
    tmux \
    terraform \
    xh \
    yq

if ! grep -q tmux /etc/shells; then
  echo
  echo "Configuring additional login shells..."
  type -P tmux | tee -a /etc/shells
fi

if ! id dk &>/dev/null; then
  echo
  passwd root
  echo
  echo "Adding local user ... dk"
  adduser -H -h /home -s $(type -P tmux) -u 501 -g dk dk
  grep '^dk:' /etc/passwd
fi

if [ ! -e /etc/ssh/ssh_host_ed25519_key ]; then
  echo
  echo "Configuring local SSH server ..."
  ssh-keygen -A
fi

services="crond local sshd"
for service in ${services}; do
  if rc-service --exists $service; then  
    rc-update add $service                
  fi               
done              
unset service