#!/bin/sh -e

if [ $(id -u) -ne 0 ]; then
  echo "This script can only be run by root!" >&2
  exit 1
elif ! type -t ufw > /dev/null; then
  echo "Command not found -- ufw" >&2
  exit 1
fi

ufw reset --force

ufw default deny incoming
ufw default deny outgoing

ufw allow out 67,68/udp       # DHCP
ufw allow out 123/udp         # NTP
ufw allow out DNS             # DNS

ufw limit in SSH              # SSH, enable brute-force protection
ufw allow out SSH             # SSH (eg: requests to clone Git repos)

if type -t mosh > /dev/null; then
  ufw allow 60000:60010/udp   # MOSH (default 60000-61000)
fi
