#!/bin/sh -e

if [ $(id -u) -ne 0 ]; then
  echo "ERROR: This script can only be run by root!" >&2
  exit 1
fi

setup-localhost

echo
/root/apply-patches

echo
echo "Updating lbu paths ..."
lbu add \
  /root/.exrc \
  /root/apply-patches \
  /usr/local
for file in $(awk '$1=="+++" { print $2 }' /root/*.patch); do
  lbu add "${file}" "${file}."*
done

echo
echo "Running setup-alpine ..."
/sbin/setup-alpine -e -f "/root/${0##*/}.answers"

if type -t dockerd-rootless > /dev/null; then
  echo
  /usr/local/sbin/setup-subids
fi
