#!/bin/sh -e

_uptime() {
  local days="$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)"
  local hours="$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)"
  local minutes="$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)"
  printf "%i days  %i hours  %i minutes" "${days}" "${hours}" "${minutes}"
}

_ip() {
  : ${1:?Missing argument -- network device}
  : ${1:?Missing argument -- ip version number}
  local ip="$(ip -${2} -o address show dev "${1}" | awk -F '[[:space:]/]*' '{ print $4 }')"
  printf "%s" "${ip}"
}

resources='  %-18s %11s %11s %11s      %s\n'
connections='  %-6s %23s %23s      %s\n'

cat << EOF
$(awk -F= '$1=="PRETTY_NAME" { print $2 ;}' /etc/os-release | tr -d '"') ($(uname -r))
Time:  $(date)
  Up:  $(_uptime)

$(printf "%-20s${resources#*s}" 'Resources:' 'Total' 'Used' 'Free')
$(free -h | awk -v row="${resources}" 'FNR>=2 { printf row, substr($1, 1, length($1)-1), $2, $3, $4 }')
$(df -ht ext4 | awk -v row="${resources}" 'FNR>=2 { if (int($5) < 65) { note="" } else { note=$5 " full" }; printf row, $NF, $2, $3, $4, note }')
$(df -ht tmpfs | awk -v row="${resources}" 'FNR>=2 { if (int($5) < 65) { note="" } else { note=$5 " full" }; printf row, $NF, $2, $3, $4, note }')

$(printf "%12s %19${connections#*3}" 'Connections:' 'Local' 'Remote')
$(ss -Htunl | awk -v row="${connections}" '{ printf row, $2, $5, $6 }')
$(ss -Htun | awk -v row="${connections}" '{ printf row, $2, $5, $6 }')

Past users:
$(last | awk -F "   +" 'FNR>=2 { if (!($1 in row)) { row[$1]=$NF } } END { for (u in row) { print "  " row[u] " - " u } }')

Load average:
  $(cat /proc/loadavg | awk '{ print "1 min - " $1 "%  5 min - " $2 "%  15 min - " $3 "%" }')

EOF
