#!/bin/sh -e
#
# Create patches with:
#   diff -dw /path/to/file.orig /path/to/file

if [ $(id -u) -ne 0 ]; then
  echo "ERROR: This script can only be run by root!" >&2
  exit 1
fi

if type -t patch > /dev/null; then
  echo "Applying root patches ..."
  for patch in /root/*.patch; do
    ( cd / && patch -ubf -p0 -i "${patch}" || true )
  done
else
  echo "Missing command -- patch" >&2
  exit 1
fi
