#!/bin/sh

ufw reset

ufw default deny incoming
ufw default deny outgoing

ufw allow out 67,68/udp       # DHCP client updates
ufw allow out 123/udp         # Network Time Protocol

ufw allow out DNS             # DNS
ufw allow out "WWW Full"      # HTTP/HTTPS

ufw limit in SSH              # SSH and enable brute-force protection
ufw allow out SSH             # SSH (req. to clone Git repos)
ufw allow in 60000:60010/udp  # MOSH (default 60000-61000)

ufw enable
